# Generated by Django 6.0.3 on 2026-03-13 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifiers', '0002_replace_udi_with_di'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='AI code (e.g. 01, 17)', max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('format_spec', models.CharField(blank=True, help_text='Format spec (e.g. N14, an..20)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Identifier',
                'verbose_name_plural': 'Application Identifiers',
                'ordering': ['code'],
            },
        ),
    ]
