# Generated by Django 6.0.3 on 2026-03-13 06:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifiers', '0003_add_ai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UDIDIPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_code', models.CharField(help_text='Generated UDI-DI-PI code per GS1 rules', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udidipi_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UDI-DI-PI',
                'verbose_name_plural': 'UDI-DI-PIs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UDIDIPIDILink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('di', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identifiers.di')),
                ('udidipi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identifiers.udidipi')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('udidipi', 'di')},
            },
        ),
        migrations.AddField(
            model_name='udidipi',
            name='dis',
            field=models.ManyToManyField(blank=True, related_name='udidipi_records', through='identifiers.UDIDIPIDILink', to='identifiers.di'),
        ),
        migrations.CreateModel(
            name='UDIDIPIAIValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identifiers.ai')),
                ('udidipi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identifiers.udidipi')),
            ],
            options={
                'unique_together': {('udidipi', 'ai')},
            },
        ),
    ]
